package puf.m2.hms.model;

import static org.junit.Assert.fail;

import org.junit.Test;

//TODO this is an example of Test case template that can be automatically generated by Eclipse
// you should do it for each class you want to test
public class PatientTest {

    @Test
    public void testPatientStringStringStringIntStringString() {
        fail("Not yet implemented");
    }

    @Test
    public void testPatientInt() {
        fail("Not yet implemented");
    }

    @Test
    public void testSave() {
        fail("Not yet implemented");
    }

    @Test
    public void testCheckExistPatient() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetPatients() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetPatientById() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetPatientByName() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetName() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetName() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetDateOfBirth() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetDateOfBirth() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetAddress() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetAddress() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetSex() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetSex() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetPhone() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetPhone() {
        fail("Not yet implemented");
    }

    @Test
    public void testGetBiographicHealth() {
        fail("Not yet implemented");
    }

    @Test
    public void testSetBiographicHealth() {
        fail("Not yet implemented");
    }

}
